### ISSUE TITLE
[font] Add frequently used fonts to a "shared" folder

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#100]
- Charis SIL
- Abyssinica SIL
- Scheherazade SIL
- Annapurna SIL

add static links and let Keyman automatically download and install the most up to date version of these font

**Comment by mcdurdin** [comment]
Notes from @LornaSIL:

Charis SIL http://software.sil.org/charis/download/
Abyssinica SIL http://software.sil.org/abyssinica/download/
Scheherazade SIL http://software.sil.org/scheherazade/download/
Annapurna SIL http://software.sil.org/annapurna/download/

These particular fonts would be used by a lot of keyboards. I noticed an old version of Abyssinica SIL went into one of the PRs. It would be easier for us to make sure we keep the font versions up to date if we put them in the shared folder. I know that SIL (the originator of the OFL) also feels that it is important to keep the files that come with the font when it is redistributed. So, it would be important to at least include OFL.txt, OFL-FAQ.txt, FONTLOG.txt and perhaps README.txt in the shared folder.

Permalinks to the font installers (zip) are:

https://wirl.api.sil.org/charissil
https://wirl.api.sil.org/abyssinicasil
https://wirl.api.sil.org/scheherazade
https://wirl.api.sil.org/annapurnasil

**Comment by mcdurdin** [comment]
Notes from @LornaSIL out of #61:

Regarding fonts:
For the release\shared\fonts would you consider using ISO 15924 codes instead of whatever someone feels like calling the script? It would be better to be standardized in that area I think. Instead of what is there now it would be: Cans, Ethi, Sinh, Taml.

If the fonts will all be in one folder we need to rethink the files that go with them. For instance, the OFL.txt goes with AbyssinicaSIL-R.ttf but no one would know that without looking in it. I cannot tell which fonts are associated with the GNU-GPLv2.txt file.

It might be best for each font distribution to have it's own folder under the 15924 script code so that the licensing doesn't get mixed up.

Also, do we need to do some thinking about whether we are legally allowed to redistribute these fonts? Certainly with some of the licenses we can. Some of the fonts don't have any license information and I would tend to think we either need to research the license or don't include them.

Our goal could be to have one very comprehensive font for each script in here and keyboards could just link to other fonts as suggestions. The problem with redistributing so many fonts is that if they are updated, we continue redistributing old versions.

**Comment by mcdurdin** [comment]
@LornaSIL Yes, your suggested folder layout makes sense. 

I do know we have done the research on all the fonts included in the repository, although the documentation on some of that research is a few years old.

There are some difficulties with updating fonts and versioning of keyboards. We should have a discussion on how we handle that.

Suggested layout:
````
release\shared\fonts\
   Ethi\
       AbyssinicaSIL-R\
           readme.MD
           AbyssinicaSIL-R.ttf
           OFL.txt ....
       ...
````

**Comment by LornaSIL** [comment]
That sounds reasonable. I don't think we need the "-R" in the folder name. Some of the fonts will have Regular, Bold, Italic, Bold-Italic so the folder name should just be the font name or font family.

**Comment by DavidLRowe** [comment]
@mcdurdin @LornaSIL Has this issue been addressed? Can it be closed?

**Comment by LornaSIL** [comment]
All of these fonts have been added to shared. We didn't go with sorting by script, we are sorting by organization, then font name. Yes, it can be closed.
