### ISSUE TITLE
[sil_ipa] Please remove the underlines from the hyperlinks in the documentation

### ISSUE THREAD

**Issue by rvkmar** [keymanapp/keyboards#1305]
The IPA (SIL) Keyboard Help document seems confusing as the default underlines for hyperlinks are confused with IPA symbols.  https://help.keyman.com/keyboard/sil_ipa/1.8.2/sil_ipa
![reportIPA](https://user-images.githubusercontent.com/29349750/90360109-5978ae80-e078-11ea-9a24-315d67fd8a37.png)

**Comment by mcdurdin** [comment]
This would need a CSS tweak, e.g. 

```
#section2 td p a {
    text-decoration: none;
}
```

While I'm at it, it looks like the HTML is malformed slightly -- before the "Other Consonants" section, there is an extraneous `</div>` which causes the section to close early (because the corresponding `<div class=WordSection1>` from the top of the document has been deleted).

Both welcome.htm and sil_ipa.php need cleanup:

* In welcome.htm, we should delete the following (found after `<h1>IPA (SIL) keyboard for Keyman Desktop</h1>`):

```
<html>
<body lang=EN-US link=black vlink=purple>

<div class=WordSection1>
```

* In sil_ipa.php, we need to add the initial heading back:

```
<h2 style='margin-top:0in'>Keyboard Layout</h2>
```

Then I think we should go through and remove all the `<div>` and `</div>` tags as they are not needed (we could keep the "ftn" divs if you like).

**Comment by LornaSIL** [comment]
@mcdurdin I'll do this. I had already done most of the work you mention in the welcome.htm but the php still has the links. Are you saying to put this into the php file?
```
#section2 td p a {
    text-decoration: none;
}
```

**Comment by mcdurdin** [comment]
> @mcdurdin I'll do this. I had already done most of the work you mention in the welcome.htm but the php still has the links. Are you saying to put this into the php file?

Thank you! Change the PHP header like so:

```
<?php
  $pagename = 'IPA (SIL) Keyboard Help';
  $pagetitle = $pagename;
  $pagestyle = <<<END
 #section2 td p a {
     text-decoration: none;
 }
  require_once('header.php');
?>
END;
```

(Rather than adding a separate `<style>` element)
