### ISSUE TITLE
Galaxie mnemonic keyboards have versioning issue

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#1465]
* The Galaxie Greek and Hebrew Mnemonic keyboard were changed to version 3.2.2
  * The webpage for Greek is still showing version 3.2.1, but the download is 3.2.2
  * The webpage for Hebrew is still showing version 3.2, but the download is 3.2.2
  * **I cannot figure out where the problem is**
* The Galaxie Greek and Hebrew Mnemonic package was changed to version 3.3
  * The webpage is still showing version 3.2.1, but the download is 3.3
  * I do see that the .kpj file has one of the version strings as 3.2.1 so that needs fixing

**Comment by DavidLRowe** [comment]
There's a similar issue for a recently updated keyboard: https://keyman.com/keyboards/engram shows a Windows download of version 1.2 (keymandesktop-13.0.116.0-engram-1.2.exe), but the version information at the bottom of the page shows version 1.1. 

I initially wondered if the problem was due to my approving the pull request with the version number not updated in the .kmn file, but it seems that it's an issue with the keyman.com site.

**Comment by LornaSIL** [comment]
@mcdurdin found the iso639-3.tab file had a problem. He patched it and notified the ISO 636-3 registrar.

**Comment by mcdurdin** [comment]
FWIW, you can check the update date and status of the database for api.keyman.com at https://api.keyman.com/. That can help to see if there is a problem with deployment or something else.
