### ISSUE TITLE
[sil_euro_latin] Add Letter N with Diaeresis to keyboard

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyboards#1485]
Guinea-Bissau Creole (pov) uses upper- and lowercase letter N with diaeresis. This can't currently be typed with the EuroLatin keyboard. Please add `n` + `:` to produce **n̈** and `N` + `:` for **N̈**.

Also, Guinea-Bissau Creole could be added to the list of supported languages.

**Comment by LornaSIL** [comment]
My question is how far we really want to take this keyboard? Do we really want it to cover the world? Or would it be better for them to have a keyboard specifically for their language?

**Comment by ermshiperete** [comment]
> My question is how far we really want to take this keyboard? Do we really want it to cover the world? Or would it be better for them to have a keyboard specifically for their language?

I don't see reason why it should not be able to put the diacritics on all characters.

But I would agree that the other question is if we want the list of supported languages to contain all languages. That makes the list pretty long. On the other hand, in the list of supported languages is already pretty long, and it contains some English- and French-based Creole languages, but no Portuguese-based. It's possible that the reason for that is that the keyboard doesn't support all the characters typically used in those languages - in which case it should be mentioned in the keyboard description.

**Comment by andjc** [comment]
To support any possible diacritic combinations is quite complex. I have
been working on such a pan-Latin keyboard. Euro_Latin would need a complete
rewrite to achieve that. A large undertaking.

Although I have written multilanguage keyboard layouts, it is better to
design language specific keyboard layouts. Better still are
orthographically responsive layouts.

Multilanguage keyboards are cumbersome, and can be very awkward to type
with for some languages. They are best suited to settings where you need
more than one language and you type infrequently in those languages.

Every time I type up extensive/large documents in a single language, I find
it necessary to redesign and improve the layout for that language, adding
typing optimisations.

**Comment by ermshiperete** [comment]
I'm not talking about adding any possible diacritic combination, just fill some holes. For example, EuroLatin supports typing a lot of characters with diaeresis but there are some holes like N with diaeresis. Similar for other diacritics.

**Comment by andjc** [comment]
From memory, although I may be wrong, Euro Latin seems to support
precomposed forms, and if I am not mistaken there is no precomposed form
for n̈.

Most Latin script languages I work with are not supported by Euro Latin,
and I would not expect them to be supported.

Euro Latin has huge gaps in Latin script support. It wasn't designed to be
a pan-Latin keyboard layout.

For the occassions I need to use a pan-Latin layout, I use something I put
together internally. Basically

1. Use options to choose between NFD and NFC output
2. Layout initially uses  combining rather than precomposed. Including
reordering diacritics  where required.
3. Map to precomposed sequences where available if NFC is required (this is
default)

It is more robust and extensible. More suited to my needs for African
languages and SE Asian languages. Especially in cases where:
* Diacritic stacking is required, or
* No precomposed forms exist.

Both weak points of Euro Latin. But then earliest versions of Euro Latin
would have not had these requirements or needs.

Although Marc or Lorna could correct and errors in my assumptions.

Euro Latin could be extended. But the extension may involve changes to the
architecture of the layout.

It may be easier and quicker to devise a layout more suited to the needs of
the languages in question.

**Comment by DavidLRowe** [comment]
The keyboard already handles p with diaersis (for which there is no precomposed character), so I used the same logic for n with diaersis (in pull request #1488).

**Comment by DavidLRowe** [comment]
@andjc Look forward to seeing your pan-Latin keyboard when it's complete.

**Comment by andjc** [comment]
@DavidLRowe currently it is internal only. Not sure there is a need for it in the repository. Esp since identifying what languages it supports would be an extensive and painful process.

Will focus more on improving language specific layouts. And developing layouts for scripts not currently supported.

**Comment by andjc** [comment]
@DavidLRowe should you have backspace rules for p̈ and n̈ in order to match precomposed characters, is delete with one keypress?

**Comment by mcdurdin** [comment]
I would like to just note that this keyboard was built originally for euro languages, and support for other languages was intentionally accidental. It is possible that other letters have been added since that were not used by European languages but every character in the original reportoire was used by at least one European language.

I would lean towards not adding support for African languages to this keyboard. There are other pan-African keyboards which would be better for that.

**Comment by DavidLRowe** [comment]
@andjc I expect backspace rules for non-precomposed character combinations would be helpful. For this change, I just copied what had been done for 'p'.
