### ISSUE TITLE
[aksarabali_panlex] some characters are shown up as boxes of question marks

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyboards#1545]
Boxes are shown inline. It does not look like they are intended.

Link: https://help.keyman.com/keyboard/aksarabali_panlex/1.1.1/aksarabali_panlex

![image](https://user-images.githubusercontent.com/28331388/117951564-7cea3480-b33e-11eb-9c4e-68967d1ccda8.png)

**Comment by LornaSIL** [comment]
These characters show up when I look at it. I suppose you need a font on your system that supports the script.
I can't remember what we need to do. Possibly add the font to s.keyman and add css to call the font in the php?

**Comment by MakaraSok** [comment]
This font is used in the keyboard, https://github.com/keymanapp/keyboards/tree/master/release/a/aksarabali_panlex/source/fonts.

We can probably use that.

**Comment by yogamardia** [comment]
Can we make the Noto Sans Balinese for this keyboard?
Font: https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansBalinese

@MakaraSok

**Comment by LornaSIL** [comment]
Vimala is the one the author of the keyboard selected. Unless we hear differently from @kamholz we should continue using the font he chose.

**Comment by kamholz** [comment]
I used Vimala because it's based in Bali Simbar (the most popular font in Bali, but not Unicode) and because Noto Sans Balinese was broken at the time. Noto Sans Balinese has since been fixed and it would actually be a good idea to add it to the Aksara Bali keyboard. My guess is that folks in Bali would prefer for Vimala to remain the default but I can ask around.

**Comment by LornaSIL** [comment]
Thanks. I'll await word from you whether to switch to Noto Sans Balinese.

**Comment by yogamardia** [comment]
As a Balinese myself, I prefer Noto Sans Balinese. Because it looks more modern and more readable on the small screen, like other Indonesian traditional script keyboard, such as Javanese script keyboard.
But I’ll await word from you whether you want to switch @kamholz

**Comment by kamholz** [comment]
I'm happy to add it to the package regardless, because the new version actually renders properly. I just want to be sure whatever the default font is respects as much of the community preference as possible since there's a range of users at this point. Noto is less traditional in style but as you say it's well suited to small sizes and screens. Given that this is for a keyboard that will be used on phones as well as desktops that's worth taking into consideration.

**Comment by yogamardia** [comment]
Sure @kamholz . Thank you for your consideration.

**Comment by LornaSIL** [comment]
This issue is related to the online help file not displaying Balinese characters. If at some point you want to include the Noto font in the keyboard package, please open a new PR.
