### ISSUE TITLE
Update Padauk font in relevant keyboards

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#19]
[Note: these keyboards are not yet in this repository - most are in internal-keyboards]

An update to Padauk (version 3.001) has been released. This version fixes a bug that changes lower ASCII characters from being marks to spacing characters. In many apps, this bug caused these characters to be stripped of their spacing and resulted in a jumble of letters. Although the intended use of this font is mainly for Myanmar script characters, this is a significant update if you ever use the Padauk font to also type Latin script characters in your documents.

Download the updated font here: http://software.sil.org/padauk/download/ 

Jon Coblentz
Non-Roman Scripts, SIL International

**Comment by LornaSIL** [comment]
PR #294 begins to fix this issue (v3.003). If a keyboard already has the Padauk font in it we will need to update the keyboard to use the "shared" Padauk font. New keyboards should use the "shared" Padauk font.

**Comment by LornaSIL** [comment]
Can't this be closed? I added the font to the shared font repo. No ```legacy``` keyboards have the font in the repo. The only ones that may still have the font in them are in the ```keyboards-internal``` repo.

**Comment by DavidLRowe** [comment]
What about release/s/shan? It seems to have a copy of Padauk.ttf (which must be an older version, since the current version has -Regular in the name). 

Would it be sufficient to remove the Padauk.ttf font from release/s/shan/source/ and add references to ../../shared/fonts/sil/padauk/*.* (to get all four .ttf files plus OFL license, etc.?
