### ISSUE TITLE
Old Hungarian keyboard make Latin leters

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1905]
@LornaSIL 
When I type on Android using Old Hungarian layout, it produce Latin letters, instead of Old Hungarian letters.
Please prepare it! You can use https://github.com/rovasiras/kende or https://github.com/kende-font/kende-font rojects' font.

**Comment by rovasiras** [comment]
@LornaSIL It seems that source codes haven't got mistakes. It maybe driver problems?

**Comment by LornaSIL** [comment]
I'm experiencing the same issue. I will look at it next week.

**Comment by rovasiras** [comment]
@LornaSIL May I ask you, that test Old Hungarian layout on other opsystem, too.

**Comment by rovasiras** [comment]
@LornaSIL Sorry, my font-repo is moved to https://github.com/rovasiras/kende-font
Named "kende" repo already exists.

**Comment by rovasiras** [comment]
@LornaSIL The Old Hungarian numbers and the Ralt+letters work. The web layout is perfect.

**Comment by LornaSIL** [comment]
@mcdurdin is this an issue because we've moved to using rules for `[NCAPS K_A]` and `[CAPS SHIFT K_A]` in the keyboard rules? On the touch layout, we have *current layer* `K_E`. Do I need to change all the rules on the touch layout to using `U_10CC4` or what is the solution?

Problem: On my android (12), Keyman 15.0.265:
- the rules that have `default K_3` are producing the Old Hungarian characters.
- the rules that have `(current layer) K_F` (etc) are producing Latin characters and not the expected Old Hungarian characters.

On the web simulator all the characters are output as expected.

**Comment by mcdurdin** [comment]
See keymanapp/keyman#6910.

**Comment by LornaSIL** [comment]
When will this update hit my Keyman app on my phone?
