### ISSUE TITLE
chore(obolo_chwerty): broken links in help

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#1912]
It looks like there are some files missing from help for obolo_chwerty 1.2.1:

```
Getting links from: http://localhost:8888/keyboard/obolo_chwerty
├─BROKEN─ http://localhost:8888/keyboard/obolo_chwerty/1.2.1/chwertyenterkey1.png (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/obolo_chwerty/1.2.1/chwertyenterkey2.png (HTTP_404)
├─BROKEN─ http://localhost:8888/keyboard/obolo_chwerty/1.2.1/chwertyenterkey3.png (HTTP_404)
Error: Process completed with exit code 1.
```

**Comment by katelem24** [comment]
I'm sorry for the not checking well.

The problem is in the filename of the three images in help.php file. Simply add "ft" between "chwerty" and "enter." So the filenames will be:
chwertyftkey1.png
chwertyftkey2.png
chwertyftkey3.png
Please confirm if that solves the issue, and help me fix it. I will do a detailed work on the welcome.htm and help.php files in the next version.
