### ISSUE TITLE
Old Hungarian layout's authors name missing.

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#1919]
@LornaSIL The Authors of Old Hungarian layout for desktop name missing. First planner is András Tisza in 2014. Lastes submitted of Old Hungarian layouts to xkeyboar-config projekt is by Viktor Kovács in the year of 2021.

**Comment by rovasiras** [comment]
@LornaSIL I have mistakes about dates.
Correct: (c) 2013 András Tisza
(c) 2017, 2018, 2020 Viktor Kovács

**Comment by LornaSIL** [comment]
The copyright will remain to SIL International since we did the work on the Keyman keyboard. However, I'll add this to the description: Keyboard for Old Hungarian. Desktop layout based on xkeyboard-config's <b>Old Hungarian (for ligatures)</b> keyboard layout by András Tisza (2013) and Viktor Kovács (2017, 2018, 2020).

That will appear on the webpage where people download the keyboard and also in the readme.htm file that is opened when people install the package. Does that sound okay?
