### ISSUE TITLE
arabic_izza touch subkeys

### ISSUE THREAD

**Issue by mhosken** [keymanapp/keyboards#193]
For the phone layout for the arabic_izza touch keyboard, there are a few sets of subkeys. My impression from the text on each key is that the author is not expecting the keys to be mapped through the kmn mapping. But they are. So the keytops are wrong for what output will happen. E.g. the K_PERIOD in the default layer has subkeys and both the K_COLON and K_BACKSLASH as listed there will output \u0650.

**Comment by DavidLRowe** [comment]
Using a K_xxx key on the touch layout will link to the definition in the .kmn file (and layer information, such as 'shift', will be passed as well). This applies to all keys, not just subkeys for a longpress definition. One solution is to use, for example, U_002C rather than K_COMMA.

**Comment by MaleBou** [comment]
arabic_izza is intended for people who use Arabic extensively on physical keyboards. The phone version hasn't been designed yet, and other keyboards could be used instead.

**Comment by DavidLRowe** [comment]
@MaleBou I sent an email with some other considerations for this keyboard, which I'd like to discuss, either here or by email. Thanks!

**Comment by MaleBou** [comment]
Dear Mr Rowe,
Thank you again for reminding me about Arabic izza keyboard.
I have dealt with all the issues you raised, and finished the design of the touch layout for both tablet and phone.
I am waiting for your answer on how to proceed in order to update the keyboard.
Kind regards,
A. Malek Bouhadjera


    On Friday, March 2, 2018, 9:08:36 PM GMT+1, DavidLRowe <notifications@github.com> wrote:  
 
 
@MaleBou I sent an email with some other considerations for this keyboard, which I'd like to discuss, either here or by email. Thanks!

**Comment by DavidLRowe** [comment]
@MaleBou 

> Dear Mr Rowe,
Thank you again for reminding me about Arabic izza keyboard.
I have dealt with all the issues you raised, and finished the design of the touch layout for both tablet and phone.
I am waiting for your answer on how to proceed in order to update the keyboard.
Kind regards,
A. Malek Bouhadjera

The best thing to do would be to create a new pull request. It should contain the changed files (revised keyboard for desktop and phone/tablet), along with any documentation changes. If you need more details, please let us know. Thanks!

**Comment by MaleBou** [comment]
All done.
