### ISSUE TITLE
Vietnamese keyboard not support auto restore non-Vietnamese word

### ISSUE THREAD

**Issue by zenfas** [keymanapp/keyboards#2080]
I use both keyboard vietnamese_telex and vietnamese_vni. Both of them don't support auto restore non-Vietnamese word 
I think should support for people sometimes need to Vietnamese and English on one document.

Thank to auther of these keyboards @miketvo

**Comment by mcdurdin** [comment]
I'm not sure what you mean by "auto restore"? The best way to type different languages in one document is to switch keyboards, because then you get the appropriate language tag for the typed text -- otherwise you get English words tagged as Vietnamese in the document.

**Comment by zenfas** [comment]
Yes, but sometimes we need type some English words not relate to Vietnamese in 1 document, with other Vietnamese input methods, if check non-Vietnamese will return what user typed in keyboard.
Example: in VN telex, type "saree" will be "sảê", "sảê" is invalid in VNese, it will return "saree". People don't need switch keyboard
Ref: https://github.com/bambooengine
https://github.com/fcitx/fcitx5-unikey
https://github.com/tuyenvm/openkey

**Comment by miketvo** [comment]
Hello @zenfas,

Thank you for your support for my keyboards.

The way I programmed my keyboards is based on the mechanism of **context** + **modifier character**. For example, to get the word "Nguyên" using Telex, one would type:

>`Nguyen` + `e` to produce `Nguyên`

In this case, `Nguyen` is the context, and `e` is the modifier character to produce the word "Nguyên". Similarly, for the word "Nguyễn", one would type:

>`Nguyen` + `e` to produce `Nguyên`, and then `Nguyên` + `x` to produce `Nguyễn`

In this case, the produced `Nguyên` becomes the context, and `x` is the modifier character to turn that context into "Nguyễn".

Essentially, my keyboards are a combinations of all possible context + modifier pairs to produce every possible Vietnamese syllables. You can check out the actual code [here](https://raw.githubusercontent.com/keymanapp/keyboards/master/release/v/vietnamese_telex/source/vietnamese_telex.kmn). As a result, typing `saree` would produce `sảê`, because the Keyman Engine recognized the `r` as the modifier for `sa` and the last `e` as the modifier for the previous `e`.

This is different from the way [BambooEngine](https://github.com/bambooengine). [fcitx5-unikey](https://github.com/fcitx/fcitx5-unikey), and [OpenKey](https://github.com/tuyenvm/openkey) are programmed, in which, from my understanding, they considered each word (separated by whitespace) as a context, and the engine keeps track of all the modification done to that context, up until a typing rule is violated, at which point the engine would turn off Vietnamese mode and revert all modifications done to that context.

With the way Keyman Engine works in the current version, I believe it is not possible to achieve the same effect without using [IMX](https://help.keyman.com/developer/15.0/guides/develop/imx/). At the time I developed vietnamese_telex and vietnamese_vni, I believe the support for IMX was not there yet, and I think it is still not ready as of now, from reading the [Keyman Blog](https://blog.keyman.com/). I might be wrong though, is that the case @mcdurdin?

If support for IMX is ready, I am more than happy to switch to using IMX instead of the current scheme, since it will be able to much more closely emulate how other Vietnamese IME works for the end-user. Meanwhile, one potential solution for @zenfas is:

> type `sarreee` to produce `saree`

Please let me know if I can further improve my keyboards by using IMX @mcdurdin.

**Comment by mcdurdin** [comment]
> Please let me know if I can further improve my keyboards by using IMX @mcdurdin.

At this stage, IMX is still Windows-only (with an undocumented, subject-to-breakage web version that works on iOS, Android and web to some extent). We do not currently have the capacity to add IMX support to other platforms, but as the team grows we hope we can tackle projects such as this one.

**Comment by mcdurdin** [comment]
> up until a typing rule is violated

You could consider tracking typing rule violations with a [deadkey](https://help.keyman.com/developer/language/reference/deadkey) or a [variable store](https://help.keyman.com/developer/language/guide/variable-stores). Deadkeys are reset whenever you change position in a document or switch focus, and have position within a document. Variable stores persist until a new session is started.

**Comment by zenfas** [comment]
@miketvo can you update icon for each Telex and VNI in next release if have, now use the same, quality not good enough.

**Comment by miketvo** [comment]
@zenfas Can you provide a screenshot?

![image](https://user-images.githubusercontent.com/73817896/206524863-4f1f2175-82c0-4f17-81e5-388c663dcbed.png)
It looks normal on my computer.

**Comment by zenfas** [comment]
> @zenfas Can you provide a screenshot?
> 
> ![image](https://user-images.githubusercontent.com/73817896/206524863-4f1f2175-82c0-4f17-81e5-388c663dcbed.png) It looks normal on my computer.

I mean each Telex an VNI methods should have its own icon, not the same. 
Current icon, "VI" should be smaller is better

**Comment by zenfas** [comment]
@miketvo Another question, can you make keyboard support change VN vowel?
Example: 
cowo => cô (now _cơo_)
tienges => tiếng (now tiengé) ! This one maybe make some people use Unikey type freedom will have error when they switch to Keyman

**Comment by DavidLRowe** [comment]
Is any action planned for this issue?

**Comment by miketvo** [comment]
I have looked into this:

> > up until a typing rule is violated
> 
> You could consider tracking typing rule violations with a [deadkey](https://help.keyman.com/developer/language/reference/deadkey) or a [variable store](https://help.keyman.com/developer/language/guide/variable-stores). Deadkeys are reset whenever you change position in a document or switch focus, and have position within a document. Variable stores persist until a new session is started.

However, because of the complexity of Vietnamese spelling, I think it is much easier to use utilize IMX to programmatically implement these complex rules.

At the more moment, I am very busy with other projects. My apology for not keeping up to date with this issue. May I inquire on the current status of IMX support @DavidLRowe? If it's ready, I can start working on this as soon as I am done with my current project, which should be in October.

For now, I don't think this issue is highly critical, since I am using my keyboard daily, and I am very used to the following workaround:

> ...Meanwhile, one potential solution for @zenfas is:
> 
> > type `sarreee` to produce `saree`
> 
> Since my keyboard does have a mechanism to cancel the latest modifier key by typing that key again right after the modification happened, but the catch is that it is limited only to the latest modifier key.

Or just switch to an English keyboard when I need to type in English. I have a hotkey combo set in Keyman to quickly do that.

**Comment by DavidLRowe** [comment]
I do not think anything has changed as far as IMX support is concerned since @mcdurdin wrote last year.

Since there are workarounds (including switching keyboards), I will close this issue for the present. It can be reopened or a new issue filed if the situation changes.

Thanks!

**Comment by miketvo** [comment]
Thank you! Please let me know if there is any update on IMX support.
