### ISSUE TITLE
Old Hungarian layout on Android in shift layer has several output mistake.

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2203]
Old Hungarian layout on Android in shift mode produce symbols instead of Old Hungarian numbers.
@LornaSIL @DavidLRowe I know, what is the problem. I'll prepared as soon as possible.

**Comment by LornaSIL** [comment]
When you use an **ID** of `K_1`, and the **Modifier** of `(current layer)` the output will be the same as what you have on the current layer (in this case `shift`) of the desktop keyboard. In this case, what you must do is change the **Modifier** from `(current layer)` to `default` (since the Old Hungarian digits are on the default layer) and it should fix the issue.
