### ISSUE TITLE
.keyboard_info cleanup

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2342]
I was looking up keyboard examples in the .keyboard_info files (while reviewing keymanapp/keyman#9459) and found two files to cleanup:

.keyboard_info files should be in root of the keyboard instead of source/
* https://github.com/keymanapp/keyboards/blob/master/release/n/northern_sierra_miwok/source/northern_sierra_miwok.keyboard_info

* https://github.com/keymanapp/keyboards/blob/master/release/fv/fv_southern_tutchone/source/fv_southern_tutchone.keyboard_info

fv_southern_tutchone may be tricky because the fv_southern_tutchone.keyboard_info is actually the touch layout used by the .kmn
https://github.com/keymanapp/keyboards/blob/595c45588b3a3a6df95597024b0c55597f5d5a62/release/fv/fv_southern_tutchone/source/fv_southern_tutchone.kmn#L26

Note: The existing fv_southern_tutchone.keyman-touch-layout has "shift" as the first layer (possibly relates to keymanapp/keyman#8718?)

**Comment by mcdurdin** [comment]
Suggested solutions:

1. northern_sierra_miwok/source/northern_sierra_miwok.keyboard_info: delete, because there is one in parent folder as well.

2. fv_southern_tutchone:
  a. delete source/fv_southern_tutchone.keyman-touch-layout
  b. rename source/fv_southern_tutchone.keyboard_info to source/fv_southern_tutchone.keyman-touch-layout
  c. fixup `&layoutfile` reference in fv_southern_tutchone.kmn
  d. ask FV team to verify the touch layout is correct.
