### ISSUE TITLE
[old_hungarian][mobile devices]mistakes with punctuation signs

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyboards#2361]
@LornaSIL There are problems with long press keys. In default layer the "main" key is decimal comma instead of reverse comma, the floating keys must to be the following, left to right:

Decimal comma,  
hyphen minus, 
double exclamation mark,
low reversed 99 quotation mark, 
high reversed 99 quotation mark, 
colon,
exclamation mark,

Next line:
base single quotation mark,
base double quotation mark,
dot,
reverse question mark,
reverse semocolon,
reverse comma.

These are on shift layer, too.

I'll follow the list in ralt layers.

**Comment by rovasiras** [comment]
@LornaSIL 
List of required sign on ralt level on 2nd line:
Change revese comma to high reverse 99 quotation mark.

3rd line:
Decimal comma produce exclamation mark, please correct it!
End of the 3rd line replace exclamation mark to double exclamation mark.

4th line: last button is empty. It could be the position of reverse comma.

**Comment by rovasiras** [comment]
Shift+Ralt level, 2nd line:one of the exclamation marks replace double exclamation marks.
 End of 2nd line is empty,  it should be reverse comma.

**Comment by rovasiras** [comment]
In the shift level decimal comma produces double qutotation mark.
Replace it to reverse comma, the longpress key for it would be same as  default level.

**Comment by rovasiras** [comment]
@LornaSIL @DavidLRowe I'm sorry, but I can't work on this for three weeks. I would like to ask You, that You prepare it. 
it's important for us that it will be perfect, and Keyman's Old Hungarian layout would be popular.

**Comment by LornaSIL** [comment]
I'll look into it, but it will be next week at the earliest.

**Comment by LornaSIL** [comment]
I'm sorry, but it isn't clear what you need. You'll need to put everything in one comment and please give the unicode codepoints, not the names.

You mention 1st, 2nd, 3rd, 4th lines. Remember that it depends on the device width how much fits on one line. It is much better not to put too many longpress keys on one key. You might consider spreading out the longpress keys onto all 3 of these keys:
![image](https://github.com/keymanapp/keyboards/assets/7071907/15e9d176-fc8a-4a6e-8f38-0dccbbb910a1)

If you want to do that, tell me something like this...this is my suggestion, but you may want it reordered:

mainkey: U+2E2E (reverse question mark)
longpress: U+0021 (exclamation)
longpress: U+203C (double exclamation mark)
longpress: U+2E42 double low-reversed-9 quotation
longpress: U+201F double high-reversed-9 quotation)
longpress: U+002E fullstop
longpress: U+003A colon

mainkey: U+2E41 (reversed comma)
longpress: U+002C (comma)
longpress: U+204F (reversed semi-colon)

mainkey: U+002D (hyphen)
longpress: U+002A (asterisk)

Actually, a lot of these are on the right-alt layers so I'm not sure you need them all on the longpress. Please try to reduce how much is on longpress if the keys are available elsewhere. It will make it easier for the user. Please put every change you want in one comment and make it clear which unicode to use. Otherwise, I cannot help you.

**Comment by rovasiras** [comment]
> I'm sorry, but it isn't clear what you need. You'll need to put everything in one comment and please give the unicode codepoints, not the names.
> 
> You mention 1st, 2nd, 3rd, 4th lines. Remember that it depends on the device width how much fits on one line. It is much better not to put too many longpress keys on one key. You might consider spreading out the longpress keys onto all 3 of these keys: ![image](https://user-images.githubusercontent.com/7071907/268761405-15e9d176-fc8a-4a6e-8f38-0dccbbb910a1.png)
> 
> If you want to do that, tell me something like this...this is my suggestion, but you may want it reordered:
> 
> mainkey: U+2E2E (reverse question mark) longpress: U+0021 (exclamation) longpress: U+203C (double exclamation mark) longpress: U+2E42 double low-reversed-9 quotation longpress: U+201F double high-reversed-9 quotation) longpress: U+002E fullstop longpress: U+003A colon
> 
> mainkey: U+2E41 (reversed comma) longpress: U+002C (comma) longpress: U+204F (reversed semi-colon)
> 
> mainkey: U+002D (hyphen) longpress: U+002A (asterisk)
> 
> Actually, a lot of these are on the right-alt layers so I'm not sure you need them all on the longpress. Please try to reduce how much is on longpress if the keys are available elsewhere. It will make it easier for the user. Please put every change you want in one comment and make it clear which unicode to use. Otherwise, I cannot help you.

Comma U+003A required only Ralt and Ralt+shift layers, because of that decimal digits required it. Hungarians use decimal comma, not decimal dot.
There are layers, which  have two exclamation maks. (U+0021) those layers change please the left ones to double exclamation mark: U+203C

**Comment by rovasiras** [comment]
@LornaSIL The elements of your suggestioned longpress keys without comma ( U+002C) is would be OK. My English is not very good.

**Comment by LornaSIL** [comment]
Here is what I have on the first longpress:
![image](https://github.com/keymanapp/keyboards/assets/7071907/e07db424-86ad-4ad4-8d4f-03e2e878e7de)

Here is what I have on the 2nd longpress:
![image](https://github.com/keymanapp/keyboards/assets/7071907/faaa10ae-a554-42ed-89a9-7ed128b6e850)

Here is what I have on the 3rd longpress:
![image](https://github.com/keymanapp/keyboards/assets/7071907/677a3af4-de0a-4418-a2ca-af2591133179)

If this is not acceptable, I **cannot** do this without you giving me extremely specific instructions on exactly what should be on the keycap and what should be on the longpress.

**Comment by rovasiras** [comment]
Thank You @LornaSIL !
It's logical and useful!
It will be on default and shifted layers, too?

**Comment by LornaSIL** [comment]
Yes, I'll do that now since you say these are okay.

**Comment by rovasiras** [comment]
@

> Yes, I'll do that now since you say these are okay.

There are okay.

**Comment by rovasiras** [comment]
@LornaSIL The default, shift, and caps layers'  longpresses didn't works ad you planned
