### ISSUE TITLE
[sil_ipa] request to add subscript numerals

### ISSUE THREAD

**Issue by sdysart** [keymanapp/keyboards#2401]
We know how to type superscript numerals, but a user wants to be able to type subscript numerals into FLEx.  Bu_phonetic seems to have this feature.

**Comment by LornaSIL** [comment]
I'm glad bu_phonetic works for what they need. 
We'll put this on the list of issues look into, but because of the complexity of the sil_ipa keyboard, we may have reached the end of the amount of keystrokes we can add. It still meets the main goal of supporting IPA and the expanded goal of supporting the phonetic requirements for China and India.

**Comment by darcywong00** [comment]
I'm briefly looking into this issue.

Maybe we can include subscript numerals on the underscore <kbd>_</kbd> rota?
