### ISSUE TITLE
[ezidi keyboard] Characters does not output accordingly to the key that is being pressed

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/keyboards#2509]
I created the Ezidi keyboard as requested here - https://community.software.sil.org/t/adding-ezidi-keyboard/8174

The font I am using seems to be a match with the PDF file they gave me - https://fonts.google.com/noto/specimen/Noto+Serif+Yezidi

> **This is the keyboard** - [yezidi.zip](https://github.com/keymanapp/keyboards/files/13736753/yezidi.zip)

---

**Keyboard information**

- The language is written from right to left based on when I typed the language on the iPhone's Telegram and the way the script is written here:
![image](https://github.com/keymanapp/keyboards/assets/90595388/4cbdff49-e244-4cb3-a1e1-241ef8b6078a)

- When tested through Keyman Developer (Test keyboard on web) and on the Keyman App (iPhone 11 pro max), it outputs the letter accordingly. 
- It's a keyboard with 4 layouts only on the Touch layout (Phone and Tablet) - this is all the [keyboard information](https://community.software.sil.org/uploads/short-url/w1foCk4mcOiVJBZetRih62pXg4D.zip) from the user so far.

---
**What's the issue**

- Testing on the iPhone's apps (Telegram and Pages) results in:
1. A previous key that was clicked is outputted after the next key is clicked twice. If the previous key was clicked 5 times then it would take 10 clicks to output those keys.
2. Sometimes, the backspace does not delete all the characters. (Telegram app).
3. Video of the issue - https://drive.google.com/drive/folders/1-2Fk9P1-6ORIQiDOgokKu-o92WjOh2Un?usp=sharing

---
**What I have tried**

- I tested two Arabic keyboards (Arabic phonetic SIL, Arabic Izza) that are written from right to left on the iPhone's Keyman App and apps (Telegram and Pages), both outputted accordingly.
- I looked into the Arabic_Izza's keyboard rules and this is the comparison. (Note: The keyboard is created according to the request and information provided above only, there are no rules for implementation.)
![image](https://github.com/keymanapp/keyboards/assets/90595388/0a0de652-2a15-4bc3-a263-250a1b2e816e)
![image](https://github.com/keymanapp/keyboards/assets/90595388/ba5bf06c-7693-4cdb-891a-b32a83a1966a)

If more information is required, I am willing to provide them.
Thank you for looking into this and for the valuable feedback.

**Comment by JanMiranKaraozan** [comment]
Hello Meng-Heng. I am trying to build a ezidi keyboard too. Could you find me via email? janmirank@outlook.com. thanks

**Comment by LornaSIL** [comment]
Thanks @Meng-Heng. I haven't figured out a solution, but I do have two suggestions for you to begin with.
- When you download the font (https://fonts.google.com/noto/specimen/Noto+Serif+Yezidi) you should not use the variable fonts. As far as I know we have not done any testing using variable fonts especially on mobile. So, in that download file there is a folder called "static" and those are the fonts we should use in the keyboard package. It is possible the problem is related to the variable font being used.
- Secondly, for the mobile layout it looks like you have created the same layout for both the tablet and the phone. If the layouts are supposed to be identical, we recommend you only include one or the other. That way you only have to update one layout and not both. It's much easier to maintain and if only one layout is available, then it will be used for both tablet and phone. However, if you want the layouts to be different on a tablet than a phone, of course you would include both. To delete one of the layouts, select "Platform: tablet" (or phone) and then click on the minus sign. That will delete that one and leave the other.

**Comment by Meng-Heng** [comment]
> Hello Meng-Heng. I am trying to build a ezidi keyboard too. Could you find me via email? [janmirank@outlook.com](mailto:janmirank@outlook.com). thanks

Hello @JanMiranKaraozan. My apology, I was not notified at all when you commented. I was helping the original author develop this as a starter boost but now I have given this project back to the original author who has continued this project. I will pass your information to them. Thank you for the email.

**Comment by Meng-Heng** [comment]
Hello @LornaSIL,

Thank you so much for the insights into the problem. My apology for not noticing your comment sooner. 
I am no longer developing this for the original author but I will share the information with them because it is pretty useful. 

I think the original author was trying to solve this by going to learn how to use Keyman App Builder. I thought it made sense because it allows Keyman to be typed on other apps but we both had limited knowledge going forward. Greatly appreciated, Lorna.

**Comment by Meng-Heng** [comment]
Update:
@LornaSIL, I believe I have removed the variable font:
![image](https://github.com/keymanapp/keyboards/assets/90595388/2f287dec-3f57-4c9d-b4cc-537fa2cb26b6)
It still does not solve the issue. Do you think it's a KAB thing? 
I will update you more when the author replies.

**Comment by LornaSIL** [comment]
>It still does not solve the issue. Do you think it's a KAB thing?

I'm not sure what "the issue" is. You also need to add the font to be selected in the .kmn file for the .kvks and for .keyboard-touch-layout and you also need to select the font in the "Keyboards" tab. Possibly those issues still need addressing. Without the current files I can't do any testing.

Also, I haven't used KAB, but once it's working properly in Keyman it should also work in KAB. If it functions correctly in Keyman and not in KAB it is possibly a KAB issue.

**Comment by Meng-Heng** [comment]
This is the keyboard package after removing the variable font and doing what you instructed:
[yezidi.zip](https://github.com/keymanapp/keyboards/files/14006197/yezidi.zip)

> I'm not sure what "the issue" is
I will explain the issue a bit clearer here.
The output is working correctly on the Keyman app for iOS but it requires two key presses to produce the first key press outside of the Keyman app (Telegram, Google docs, Pages).

**Comment by LornaSIL** [comment]
I went ahead and created a pull request #2522 for this issue. I made changes to the files as documented in the PR. I think the keyboard should work now, but you can test it either by pulling and doing a build, or I've included the .kmp in the attached zip file. There were two main issues, the language tag wasn't correct and the fonts weren't in the location you indicated (because they were on your system, and not mine). I've added the fonts to the `release\shared\noto\Yezi` folder so that future Yezidi keyboards can benefit from having the fonts available.

[yezidi.zip](https://github.com/keymanapp/keyboards/files/14012292/yezidi.zip)

If it looks good, you can let me know and I'll remove the "work-in-progress" label. If it doesn't look good, you can use my pull request to make changes. That way we can have a stable source and see changes more easily.

**Comment by Meng-Heng** [comment]
Everything is working and outputting on the Keyman app so I'm pleased with the result @LornaSIL.
There has not been an update from the author so I'm happy to close this issue.

I will let the original author implement any changes they want or report any issues going forward.
Thank you.

**Comment by Meng-Heng** [comment]
The keyboard is [available](https://keyman.com/keyboards/yezidi)! 

Check #2522 for more information
