### ISSUE TITLE
bug(ci): font deployment does not copy fonts in sub-folders

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#2531]
https://help.keyman.com/keyboard/yezidi/1.0/yezidi

![image](https://github.com/keymanapp/keyboards/assets/4498365/5df1dc1f-9de1-41fa-be9f-a9db44cf7467)

**Comment by LornaSIL** [comment]
It doesn't appear that the "shared" fonts are automatically getting deployed here anymore: `s.keyman.com\font\deploy`. Is that a bug or did something slip through the cracks? I stopped doing a separate commit to that repo with new fonts because I thought the `keyboards\release\shared\fonts` were getting auto deployed to `s.keyman.com\fonts\deploy`.

**Comment by LornaSIL** [comment]
I updated or added a lot of fonts in December. This commit should have included a font, but it's just the .js file:  [896e392]

**Comment by mcdurdin** [comment]
OK, I'll dig in and find out why the fonts were not included in that deploy. I'll repurpose this issue for tracking that

**Comment by mcdurdin** [comment]
OK, found the issue. The fonts in subfolders are not being copied over. This should be a relatively straightforward fix -- all the fonts on s.keyman.com must be in the same folder at this time, so we'll just copy them all into the one flat folder.

**Comment by LornaSIL** [comment]
My coworkers all verify they see the correct glyphs and not tofu.
