### ISSUE TITLE
HEX 2019 for ISO-15919 Avagraha transcription not available please add

### ISSUE THREAD

**Issue by gregjay** [keymanapp/keyboards#2539]
[itrans_roman.keyboard](https://github.com/keymanapp/keyboards/blob/master/release/itrans/itrans_roman/itrans_roman.keyboard_info) purports to support both IAST and ISO-15919. However while "'" is used in IAST for Avagraha. HEX 2019 is used in ISO-15919. Please provide in a future version a simple way to type Avagraha HEX 2019 for use in ISO-15919 transliteration.

Thank you

Greg

**Comment by mcdurdin** [comment]
Would you be willing to submit a pull request that implements this change? I assume you mean Unicode character U+2019 (`’`) representing Devangari Sign Avagraha (`ऽ`, U+093D)?

https://help.keyman.com/developer/keyboards/ has some instructions on how to submit a pull request

**Comment by gregjay** [comment]
I don't know what a pull request is. But sure I'm willing to do it.
Yes, I want to use your keyboard for ISO-15919 input but I need U+2019
which is the ISO transliteration of Avagraha (U+093D).

I just went through your help file for your keyboard and it states that
transliteration of Avagraha (U+093D) to Latin letters is U+0027 for both
IAST and ISO.
This is incorrect. It is correct transliteration for IAST but NOT for ISO.
I'm just suggesting you add a simple way to type U+2019 which is the actual
Latin transliteration of Avagraha (U+093D) according to ISO-15919.

Cheers

Greg

**Comment by Meng-Heng** [comment]
Hello @gregjay,

We will make changes and create a pull request on your behalf. You can guide us through what needs to change?
If not mistaken, the section shown below is where the change needs to be?
![image](https://github.com/keymanapp/keyboards/assets/90595388/3ad30068-3b82-41c4-bf58-16ee5e25a39a)
Feel free to show the correct form if the changes below are incorrect.
![image](https://github.com/keymanapp/keyboards/assets/90595388/156c2a04-fd32-40a6-9189-beac8858ea27)
We went for this change instead of adding a dedicated key for U+2019 because of the convenience of typing (U+0027) > ’ > ʼ > (U+0027).

Changes are made for the keyboard too, here are the sequences:
- type <kbd>'</kbd>, it would output <kbd>'</kbd>(U+0027). 
- continue to type <kbd>'</kbd> two times, it would output <kbd>’</kbd>(U+2019).
- continue to type <kbd>'</kbd> three times , it would output <kbd>ʼ</kbd>(U+02BC).
- type the fourth time, it would go back to <kbd>'</kbd>(U+0027).

The extra <kbd>ʼ</kbd>(U+02BC) is not going to represent anything, it appears to look the same but has a different Unicode.

Let us know whether this change suits your usage for ISO.

**Comment by gregjay** [comment]
Thank you

A. These solutions are very good. I need only U+0027 for IAST and U+2019
for ISO.
B. I understand why you want to add U+02BC but I feel that it will be
confused by some for U+2019 as it appears to be the same glyph even though
it is not the same Unicode point.
C. As for typing 4 times to return to U+0027 I think this is unnecessary as
1 time will be enough.

Thus I feel that since the purpose of your keyboard is to represent IAST
and ISO diacritics only Solution A. above is required.
Your ideas for B. and C. above are adding confused and redundancy in my
opinion, but it's your keyboard and even adding these ideas would not be a
problem for me.
Solution B. might be a problem for others who want to take a text created
with your keyboard and transcribing it automatically with a site like
Aksharamukha or another utility.
If they are unable to see the difference between U+2019 and U+02BC then
there might be problems changing to Indic scripts primarily Devanagari.

Thanks for all your help and suggestions.
If you can let me know when the next version is available I would be very
grateful.

Greg

**Comment by DavidLRowe** [comment]
IIUC the keyboard already cycles through U+0027 and U+02BC. Perhaps a simpler solution would be to change the U+02BC to U+2019. (As you note, often the two are visually similar or identical in a given font, and it could be a source of confusion to have both.)

Can you point to an online reference to ISO-15919 that could be cited in the notes for this change? Thanks!

**Comment by LornaSIL** [comment]
Fixed by #2546

**Comment by gregjay** [comment]
When will Indic Keyboard for Itrans be updated?
After receiving this message stating Fixed I deleted the keyboard then
downloaded it again and installed it again.
There was no change. Even though the keyboard help file on the net says it
has been fixed.

Greg

**Comment by mcdurdin** [comment]
@gregjay investigating why the keyboard has not yet been published. We just did a major upgrade of our websites so it's probably related to that. Will update once I have some detail.

**Comment by mcdurdin** [comment]
@gregjay The deployment problem has been resolved and version 1.2.0 should be available now.

**Comment by gregjay** [comment]
Thank you. I tried the new deployment version 1.2.0 seems great.
I'll let you know if I have any further suggestions

Greg
