### ISSUE TITLE
[gff_gurage_legacy] Current version 0.5 is "older" than the previous 0.11

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#2720]
In keymanapp/keyboards#2719, I updated some pagenames/pagetitles for some of the keyboard help.

The auto PR keymanapp/help.keyman.com#1211 should have synced the latest versions of the keyboards.
But [gff_gurage_legacy.php](https://github.com/keymanapp/help.keyman.com/pull/1211/files#diff-d72671e791245f17751ddf37c45e81f85c427f61b438c98f7d4fc9f3f56ad013) updated version 0.5 instead of the latest 0.11.

**Comment by LornaSIL** [comment]
What's the best way to handle this? Should we change it to version .51? I
don't think the author wants to move it to 1.0 yet.

**Comment by darcywong00** [comment]
yeah, bumping the version to .50 should work.

**Comment by dyacob** [comment]
If I follow, the version number, 0.5, did not get set everywhere?  Sorry for that.  Ideally, the overlooked places could all go to 0.5 .  If a _new_ version is necessary, then 0.50 (just an extra "0" padding) would be my preference or "0.51" if the padding isn't sufficient.

**Comment by mcdurdin** [comment]
Version numbers are not decimals. They are dot separated integers. So 50 is greater than 11.

**Comment by mcdurdin** [comment]
0.5.0 is older than 0.11 though

**Comment by LornaSIL** [comment]
But 0.50 is bigger than 0.11

**Comment by mcdurdin** [comment]
0.5.0 is equivalent to 0.5

**Comment by dyacob** [comment]
I'm understanding better now.  The `0.11` was a mistake on my part, thinking it was like `0.1.1` .  Now however, `0.11` looks newer than `0.5` because 11 > 5.  Thus some number greater than 11 is needed for a listing to show the latest version properly.  

Until a 1.0 version is reached, could we continue with the broken convention and make an update be `0.51` ?   I think this should work since 51 > 11 .

**Comment by mcdurdin** [comment]
Yep that will work!

**Comment by LornaSIL** [comment]
Fixed by #2730
