### ISSUE TITLE
font(kbdkhmr or busrakbd)

### ISSUE THREAD

**Issue by LornaSIL** [keymanapp/keyboards#3231]
@mcdurdin your feedback?

I thought this was the font we chose to use for remapping the OSK for Khmer: `release\shared\fonts\kbd\kbdkhmr`

If that is the case, we should consider removing this one from the repo (and from the s.help repo):
`release\shared\fonts\khmer\busrakbd`

If we want to keep both fonts, we should move `busrakbd` to go under the `kbd` folder so no one gets tempted to use it for anything other than the OSK remap.

I would be interested to know what the differences are in the two fonts and why we need both.

**Comment by mcdurdin** [comment]
busrakbd was the first experimental font we used before we had completed the `&displaymap` feature. So, yes, we should deprecate and remove that one and instead use `&displaymap` correctly as we have done in the khmer_angkor keyboard. This will mean updating e.g. the sil_jarai keyboard to use the Khmer range codepoints rather than the PUA codepoints that are currently in the .kvks and .keyman-touch-layout files. I haven't audited the other keyboards. @Nnyny, can you check the other Khmer script keyboards for use of the busrakbd font? Happy to discuss with you further if you need more detail 😁

**Comment by mcdurdin** [comment]
Note: we won't remove the existing font from the s.keyman.com repo, because policy is never to delete from that repo -- we don't know who is using what and so we maintain a stability policy for that repo. (We do have a problem with font versions on s.keyman.com, but that's yet another problem for yet another day)

**Comment by Nnyny** [comment]
Yes, @mcdurdin. I'll look into other keyboards.

**Comment by Nnyny** [comment]
I have went through all keyboards which use Khmer script and there is only sil_jarai that still use Khmer Busra Kdb for Touch Layout in .kmn file. Others are using KbdKhmr font.

**Comment by mcdurdin** [comment]
> I have went through all keyboards which use Khmer script and there is only sil_jarai that still use Khmer Busra Kdb for Touch Layout in .kmn file. Others are using KbdKhmr font.

That's good news. Given that, can you delete the Khmer Busra Kbd font from the repository in #3243 please?

**Comment by Nnyny** [comment]
Done!

**Comment by mcdurdin** [comment]
Looks like Khmer Busra Kbd was not deleted in #3243 after all -- so we'll need to do that as a follow-up

**Comment by Nnyny** [comment]
@mcdurdin, I already deleted the font from sil_jarai keyboard folder. Do I also have to delete Khmer Busra Kbd from `keyboards\release\shared\fonts\khmer` ?

**Comment by mcdurdin** [comment]
> Do I also have to delete Khmer Busra Kbd from `keyboards\release\shared\fonts\khmer` ?

Yes please
