### ISSUE TITLE
[infrastructure] Metadata quality work

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#335]
## release/ keyboard_info
- [ ] Add descriptions
- [ ] Remove unncessary fields
- [ ] Verify platform info

## for all keyboard_info
- [ ] Validate list of keyboards vs in .kmn, .kps

## Missing examples
- [ ] georgian missing keyboard example from cloud
- [ ] grkpoly2 (and possibly language associations
- [ ] hieroglyphic
- [ ] isis
- [ ] kburdu
- [ ] how many more?

## Sort out qxx codes
- [ ] Replace with correct language-region code 
- [ ] e.g. canadian_french

## cs-pinyin
- [ ] is Windows only. (what's to fix?)

## isis
- [ ] missing metadata from r.keymanweb.com
(this may be because they were both available in Keyman Desktop and KMW. see isis_devangari)

**Comment by DavidLRowe** [comment]
@darcywong00 This has been in the "To do" list for over two years. I think some of the items have been addressed as individual keyboards were updated. cs-pinyin is on Marc's long-term "to do (or not)" list (see #64, also 219). I know that many keyboards do not have examples, but I didn't think it was a requirement.

I'm not sure what the next step is. Should we close this issue and create a new one with a list of metadata problems? Who would do that?

**Comment by darcywong00** [comment]
I would defer to @mcdurdin on which items in the issue are a priority.

**Comment by mcdurdin** [comment]
I think we go ahead and close this. There is not a screaming problem with any of these items, and remaining issues can be addressed over time with other maintenance on affected keyboards.

Adding that initial keying example would be a good thing to do, IMHO, because it really kickstarts getting started using the keyboard. We currently only display that example on keymanweb.com but we could start to include it in apps as well in the future.

**Comment by DavidLRowe** [comment]
I'd suggest that a first step would be an example (KB, blog, help page, or something) with a few tips on what a good example might be. Then we might want to change the template in Keyman Developer so that something is included in the .keyboard_info file for a new project.
