### ISSUE TITLE
[cheyenne] Deprecate keyboard and replace with chey-unicode

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyboards#340]
From https://community.software.sil.org/t/please-delete-old-cheyenne-keyboard/987
 > Please delete the old Keyman Cheyenne keyboard from this webpage:
>
>https://secure.tavultesoft.com/keyman/downloads/keyboards/search.php?Submit=search&Search=cheyenne&x=34&y=16
>
>I am working with the Cheyenne tribe right now and they are confused about which keyboard to download for typing their language. The old keyboard was designed before Unicode was available and required use of three special fonts designed by SIL. Several Cheyennes have downloaded both keyboards but they find this confusing. Since most Cheyennes today do not have the old SIL fonts, the old keyboard produces wrong results.
>
>It would be fine to rename the remaining “Cheyenne - Unicode” keyboard to simply “Cheyenne”.

------------------

Also, from a separate PM.

Currently, their Keyman Android users use the European2 keyboard (listed under the "Aleut" language). We should be able to associate "Cheyenne" (chy?) in the metadata for the keyboard.

**Comment by LornaSIL** [comment]
Wayne sent me the source file for Chey-Unicode at the end of April and gave permission to move it to MIT license. It just hasn't made it to the top of my priorities. I'll work on doing this.

**Comment by darcywong00** [comment]
More input from Wayne if we don't remove `Cheyenne`.

> If you keep the old Cheyenne keyboard, please try to position it on the Cheyenne keyboard page so that it does not show up right away. Please rename it to something like “Cheyenne - old keyboard that requires fonts no longer available”. Then please rename the good keyboard as simply “Cheyenne”. Cheyennes do not understand technical labels so they are confused by words like Unicode. We have been using Keyman for many years. Cheyennes are finding it helpful as they become more computer literate. Thank you to all the Keyman team for maintaining Keyman and its keyboards for many years with different operating systems

**Comment by mcdurdin** [comment]
Copying my comment from community discussion:

Here’s my thoughts on this:

1. I’m not keen on removing keyboards because there will always be someone who needs to edit old data.
2. We can certainly make it much clearer that the Cheyenne (non-Unicode) keyboard is obsolete. We can update the keyboard_info for both keyboards and that should make this a lot clearer.
3. We should not mark the Cheyenne keyboard as ‘deprecated’ by the Cheyenne Unicode keyboard, because they are not compatible: you cannot edit old Cheyenne non-Unicode data with the Cheyenne Unicode keyboard.
4. Yes, as Darcy notes, this maintenance will be more visible in a few weeks when the old keyboard search is retired.

So, my suggestion is we clarify the description on both keyboards to make it clear that you shouldn’t install the old keyboard unless you know what you are doing :slight_smile:

**Comment by LornaSIL** [comment]
I think it's already clear that the old one is obsolete:
https://keyman.com/keyboards/cheyenne

AND it links to the new one:
https://keyman.com/keyboards/sil_cheyenne/

So, I'm closing this issue.
