### ISSUE TITLE
Delete Cameroon Qwerty Unicode.

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyboards#650]
The old Cameroon Qwerty Unicode is vestigial and broken and does not contain the fixes made over the last 10 years, but it still comes up first in many searches.
https://help.keyman.com/keyboard/cameroonqwertyunicode50/1.1/cameroonqwertyunicode50.php
Please either delete any reference to this old keyboard (preferred), or make the documentation and download pages redirect immediately to Cameroon QWERTY (SIL). I'm tired of support requests from people accidentally downloading the wrong keyboard. It does not need to exist.

**Comment by darcywong00** [comment]
This request is similar to #340 

The internal Keyman keyboard search 
https://keyman.com/keyboards?q=cameroon

has the order
1. sil_cameroon_azerty
2. sil_cameroon_qwerty
3.. cameroonqwertyunicode50

And https://keyman.com/keyboards/cameroonqwertyunicode50 does have the markings that the keyboard is deprecated and for users to use sil_cameroon_qwerty instead.

**Comment by erros84** [comment]
I see the markings, but they are in English and will be ignored. Can you completely delete it for me? There is no reason that anyone should be using the old one. I understand keeping the non-unicode versions for historical reasons, but I want cameroonqwertyunicode50 to be impossible to download accidentally. If it is better from an SEO perspective to keep the old link, @DavidLRowe said it might be possible for the site to forcefully redirect to sil_cameroon_qwerty if you try to access the dead page.
![image](https://user-images.githubusercontent.com/986339/55047761-e2babb80-5013-11e9-9f23-5287daaf960e.png)

**Comment by mcdurdin** [comment]
I understand the issue. I agree that the scenario is different to that in #340. This is not the only keyboard for which we have this problem.

In the future, the intent is for the deprecation pathway to allow Keyman Desktop to automatically upgrade from the legacy version to the new version, both at install time and later during regular automatic updates.

But this is a little more complicated than it might seem. That third link in your Google search will give a 404 if we just delete the keyboard. We don't have infrastructure in place to do a redirect and I don't want to start adding that piecemeal because we end up over time with lots of special cases that we cannot maintain. That was a large part of how we ran into trouble with maintaining the old keyboards repository, so this is not just a spurious concern.

I can see three mitigations or solutions that we could consider here:

1. Make the "deprecated banner" into a "download the new version banner", which shows with a green download button, and takes them to the correct version (they'd have to click Download again though on the new page). Then hide the downloads for the deprecated version, and make them accessible only by clicking a subtle link which does a javascript unhide of the content. I understand that we don't really need users to be able to access this version, but this is a generalised solution to deprecation that does work for all scenarios. Time to create solution: 1 hour.

2. Add deletion infrastructure to the keyboards repository, such that we can add redirects for legacy, deleted keyboards, to their replacements. Ideally, there would be some sort of messaging on the final landing page that indicates why the user ended up at a keyboard that doesn't match what they clicked on. This requires changes to the keyboards repository, the website, and the api site, in order to work completely. Time to create solution: 1 week.

3. Implement the automatic upgrade of deprecated keyboards in Keyman apps (all platforms). Time to create solution: 1 month.

I think it is probably pretty obvious which mitigation I am leaning towards at this time. I can foresee us implementing all three of these solutions at some point. @erros84 will option 1 provide enough of a solution for now? There are other possibilities but I think they will be similar in scope to options 2 or 3.

**Comment by erros84** [comment]
Thanks Marc,
I am happy with Option 1, which should solve the immediate problem for now. 
I do see the SEO value of retaining well-ranked URLs (though I would expect that eventually with a 301 redirect the search engine will get the idea and reprioritize the new link), and appreciate that it will point (for now) more obviously to the relevant content and may eventually redirect to the same content. I will also be happy to ride the wave whenever option two and three are implemented. 
I understand that deprecated keyboards are not your biggest priority. Option 1 is a better band-aid for now. :) 
~M

**Comment by mcdurdin** [comment]
Great! I've made the changes in https://github.com/keymanapp/keyman.com/pull/14 and once merged they should be visible to all. Here's what it looks like:

![image](https://user-images.githubusercontent.com/4498365/55365444-52f3a080-5530-11e9-985c-b4e010610aaa.png)

**Comment by erros84** [comment]
Instant deprecation! Thanks. I can close this when it goes live.

**Comment by mcdurdin** [comment]
The change has now been merged :)

**Comment by erros84** [comment]
Thanks team!
