### ISSUE TITLE
[FirstVoices] Dakelh keyboard touch layout is wrong (default)

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyboards#916]
I have a report that the Dakelh keyboard has the wrong outputs from the default layer. I have not yet tried to replicate but wanted to record this so I didn't lose the information.

**Comment by DavidLRowe** [comment]
There are a number of problems with this keyboard.  Some longpress keys on the full stop key (both default and shift layers) produce the wrong characters, most likely because they are picking up the redefined keys from the .kmn file. These issues could probably be fixed by someone who isn't familiar with the language / keyboard.

In addition, however, the underlined z, dz, ts, s characters (which have separate keys on the desktop layout) do not have separate keys on the touch layout, and it's not clear how one would type those characters. I expect that adding these four keys to the touch layout (default and shift layers) would need input from the language community.

**Comment by mcdurdin** [comment]
Thank you as always @davidlrowe for your comprehensive and detailed documentation of the issues!

**Comment by DavidLRowe** [comment]
But it's not clear how to proceed. Do we fix up the immediate problems with the touch layout and leave the additional keys issue to someone else? Or wait for someone to fix everything? Any thoughts?

**Comment by mcdurdin** [comment]
I think we should fix the immediate issues in a PR; meanwhile I will ask the FirstVoices team to review your comments regarding the additional keys and see what they advise. If we get a quick turnaround on that we can incorporate their answer into the PR.
